T = int(input('Digite um número para ver a tabuada - '))

print('-'*12)
print("{} x  1 = {}".format(T, T))
print("{} x  2 = {}".format(T, T*2))
print("{} x  3 = {}".format(T, T*3))
print("{} x  4 = {}".format(T, T*4))
print("{} x  5 = {}".format(T, T*5))
print("{} x  6 = {}".format(T, T*6))
print("{} x  7 = {}".format(T, T*7))
print("{} x  8 = {}".format(T, T*8))
print("{} x  9 = {}".format(T, T*9))
print("{} x 10 = {}".format(T, T*10))
print('-'*12)
